### ISSUE TITLE
Splice Leader

### ISSUE THREAD

**Issue by bkellman** [elsayed-lab/utr_analysis#4]
How do I find the splice leader for a novel organism? I'm working with CHO cells.

**Comment by khughitt** [comment]
HI @bkellman,

Did you take a look at the README.md? There are some example commands there which you should be able to modify for use with your system.

This pipeline was designed primarily for detection of parasite spliced leader and poly(a) sites. I take it that CHO is your host cell - is there a pathogen you are interested in detected SL sites for? If so, is there a reference genome for that organism?

**Comment by bkellman** [comment]
I see, it seems I have misunderstood the purpose of this package. I'm interested in characterizing the 5' and 3' UTRs of the mRNA in the CHO cells. CHO cells do have a reference. Do you know of a package that can help me characterize the 5' UTR or should I just try extracting a 5' UTR gff and run the reads through tophat?

**Comment by khughitt** [comment]
@bkellman I don't know of any such tools off the top of my head, but I believe I've seen some articles at least looking at the 3'UTR side. Here is one possible tool for Poly(A) detection:

[3USS: a web server for detecting alternative 3′UTRs from RNA-seq experiments](http://bioinformatics.oxfordjournals.org/content/31/11/1845.short) (Le Pera et al., 2015).

In CHO, detecting the 5'UTR boundary will be more challenging since there is no unique SL sequence at the 5' end of each mRNA that can be used for detection.

A good place to get suggestions might be either [Biostars](https://www.biostars.org/) or the [Bioconductor support forums](https://support.bioconductor.org/t/Latest/).

Goodluck!
